// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

type Tag struct {
	ID        int64
	Name      string
	CreatedAt string
}

type Todo struct {
	ID        int64
	Title     string
	Body      string
	Done      int64
	CreatedAt string
	UpdatedAt string
}

type TodoTag struct {
	TodoID int64
	TagID  int64
}
