// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	AddTodoTag(ctx context.Context, arg AddTodoTagParams) error
	CreateTag(ctx context.Context, name string) (Tag, error)
	DeleteTag(ctx context.Context, id int64) error
	GetTag(ctx context.Context, id int64) (Tag, error)
	GetTagByName(ctx context.Context, name string) (Tag, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsByTodoID(ctx context.Context, todoID int64) ([]Tag, error)
	RemoveTodoTag(ctx context.Context, arg RemoveTodoTagParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
