// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"
)

const addTodoTag = `-- name: AddTodoTag :exec
INSERT OR IGNORE INTO todo_tags (todo_id, tag_id) VALUES (?, ?)
`

type AddTodoTagParams struct {
	TodoID int64
	TagID  int64
}

func (q *Queries) AddTodoTag(ctx context.Context, arg AddTodoTagParams) error {
	_, err := q.db.ExecContext(ctx, addTodoTag, arg.TodoID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, created_at
FROM tags
WHERE id = ?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, created_at
FROM tags
WHERE name = ?
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByTodoID = `-- name: ListTagsByTodoID :many
SELECT t.id, t.name, t.created_at
FROM tags t
INNER JOIN todo_tags tt ON t.id = tt.tag_id
WHERE tt.todo_id = ?
ORDER BY t.name ASC
`

func (q *Queries) ListTagsByTodoID(ctx context.Context, todoID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTodoTag = `-- name: RemoveTodoTag :exec
DELETE FROM todo_tags WHERE todo_id = ? AND tag_id = ?
`

type RemoveTodoTagParams struct {
	TodoID int64
	TagID  int64
}

func (q *Queries) RemoveTodoTag(ctx context.Context, arg RemoveTodoTagParams) error {
	_, err := q.db.ExecContext(ctx, removeTodoTag, arg.TodoID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = ?
WHERE id = ?
RETURNING id, name, created_at
`

type UpdateTagParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag, arg.Name, arg.ID)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
