// 이 파일은 "sqlc 코드 생성 규칙"을 검사한다.
//
// sqlc란?
//
//	sqlc는 SQL 쿼리 파일(.sql)을 읽어서 Go 코드를 자동 생성해주는 도구다.
//	NestJS/TypeScript 생태계의 Prisma와 비슷한 역할을 한다.
//	차이점: Prisma는 스키마 파일에서 모델+쿼리를 자동 생성하지만,
//	sqlc는 개발자가 직접 작성한 SQL 쿼리를 Go 코드로 변환한다.
//	즉, SQL을 직접 제어하면서도 타입 안전한 코드를 얻을 수 있다.
//
// sqlc.yaml이란?
//
//	프로젝트 루트에 있는 sqlc의 설정 파일이다.
//	어떤 디렉토리의 .sql 파일을 읽어서, 어디에 Go 코드를 생성할지 정의한다.
//	도메인을 추가할 때마다 sqlc.yaml에 새 항목을 등록해야 한다.
//
// 이 파일에서 검사하는 3가지 규칙:
//
//  1. sqlc/missing-sqlc-entry (ERROR)
//     - repo/ 디렉토리에 .sql 파일이 있지만, sqlc.yaml에 해당 경로가 등록되지 않은 경우
//     - .sql 파일이 있다는 것은 sqlc를 쓰겠다는 의도인데, 설정이 누락된 것이다
//
//  2. sqlc/manual-code-in-sqlc-repo (ERROR)
//     - sqlc를 사용하는 repo/ 디렉토리에 수기 작성된 .go 파일이 있는 경우
//     - sqlc가 생성한 파일에는 반드시 "Code generated by sqlc. DO NOT EDIT." 헤더가 있다
//     - 이 헤더가 없는 .go 파일은 개발자가 직접 작성한 것이므로 위반이다
//     - repo/의 Go 코드는 모두 sqlc가 자동 생성해야 한다. 비즈니스 로직은 svc/에 작성.
//
//  3. sqlc/orphan-sqlc-entry (WARNING)
//     - sqlc.yaml에 항목이 있지만 해당 디렉토리에 .sql 파일이 없는 경우
//     - 도메인이 삭제되었지만 sqlc.yaml에서 항목을 빼지 않은 것일 수 있다
package ruleset

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	// gopkg.in/yaml.v3는 Go에서 YAML 파일을 읽고 쓰기 위한 서드파티 라이브러리다.
	// Go 표준 라이브러리에는 JSON 파서(encoding/json)는 있지만 YAML 파서는 없다.
	// Node.js의 js-yaml 패키지와 비슷한 역할이다.
	"gopkg.in/yaml.v3"

	"rest-api/test/architecture/report"
)

// ──────────────────────────────────────────────
// sqlc.yaml 파싱을 위한 구조체 정의
// ──────────────────────────────────────────────

// sqlcConfig는 sqlc.yaml 파일의 전체 구조를 나타내는 구조체다.
//
// Go에서 YAML/JSON을 파싱하려면, 파일 구조에 맞는 구조체를 정의하고
// "태그(tag)"로 필드와 YAML 키를 매핑한다.
//
// 구조체 태그(struct tag)란?
//
//	필드 옆에 `yaml:"sql"` 형태로 붙이는 메타데이터다.
//	yaml.Unmarshal이 YAML을 파싱할 때 이 태그를 보고
//	YAML의 "sql" 키 값을 SQL 필드에 넣어준다.
//	NestJS/TypeScript에서 class-transformer의 @Expose({ name: "sql" })와 비슷하다.
//
// sqlc.yaml 예시:
//
//	version: "2"
//	sql:                                          ← sqlcConfig.SQL
//	  - queries: "internal/domain/user/.../repo/"  ← sqlcEntry.Queries
//	    schema: "internal/db/migration/"
//	    engine: "sqlite"
//	    gen:
//	      go:
//	        package: "repo"
//	        out: "internal/domain/user/.../repo/"
//
// 여기서는 검증에 필요한 최소 필드(sql, queries)만 정의한다.
// YAML 파서는 구조체에 없는 필드는 무시하므로 문제없다.
type sqlcConfig struct {
	SQL []sqlcEntry `yaml:"sql"` // YAML의 "sql" 키 → Go의 SQL 필드
}

// sqlcEntry는 sqlc.yaml의 sql 배열 안에 있는 각 항목을 나타낸다.
// 검증에 필요한 것은 queries 경로뿐이므로 이것만 정의한다.
type sqlcEntry struct {
	Queries string `yaml:"queries"` // .sql 파일이 위치한 디렉토리 경로
}

// ──────────────────────────────────────────────
// 메인 검사 함수
// ──────────────────────────────────────────────

// CheckSqlc는 sqlc 관련 3가지 규칙을 모두 검사한다.
//
// CheckStructure와 같은 패턴으로, *Config만 받아서 직접 파일시스템을 스캔한다.
// (CheckDependencies나 CheckNaming처럼 미리 파싱된 파일 목록을 받지 않는다.)
//
// 검사 흐름:
//  1. sqlc.yaml을 파싱하여 등록된 경로 목록을 가져온다
//  2. internal/domain/**/repo/ 디렉토리를 탐색하여 .sql 파일이 있는 곳을 찾는다
//  3. 세 가지 규칙을 각각 검사한다
func CheckSqlc(cfg *Config) []report.Violation {
	var violations []report.Violation

	// ── 1단계: sqlc.yaml 파싱 ──
	// 파일이 없거나 파싱에 실패하면 빈 설정으로 처리한다.
	// (sqlc.yaml이 없는 것 자체는 에러가 아님 — 아직 sqlc를 안 쓰는 프로젝트일 수 있다)
	sqlcCfg, err := parseSqlcYaml(cfg.ProjectRoot)
	if err != nil {
		// 파싱 실패 시 빈 설정으로 대체하여 나머지 규칙은 계속 검사한다
		sqlcCfg = &sqlcConfig{}
	}

	// ── 2단계: sqlc.yaml에 등록된 queries 경로들을 Set으로 만든다 ──
	//
	// map[string]bool을 "Set" 자료구조로 사용하는 Go 패턴이다.
	// Go에는 Set 타입이 없어서, map의 키를 집합 원소로 쓰고 값은 항상 true로 둔다.
	// TypeScript의 Set<string>과 같은 용도:
	//   TS:  const set = new Set(["a", "b"]);  set.has("a") → true
	//   Go:  set := map[string]bool{"a": true, "b": true};  set["a"] → true
	//
	// filepath.Clean은 경로를 정규화한다. 예: "a/b/../c" → "a/c", "a/b/" → "a/b"
	// 경로 비교 시 동일한 디렉토리가 다른 문자열로 표현되는 문제를 방지한다.
	registeredPaths := make(map[string]bool)
	for _, entry := range sqlcCfg.SQL {
		cleaned := filepath.Clean(entry.Queries)
		registeredPaths[cleaned] = true
	}

	// ── 3단계: .sql 파일이 있는 repo/ 디렉토리들을 찾는다 ──
	sqlRepoPaths := findSQLRepoPaths(cfg.ProjectRoot)

	// ── 규칙 1: sqlc/missing-sqlc-entry ──
	// .sql 파일이 있는 repo/가 sqlc.yaml에 등록되어 있는지 확인한다.
	for _, repoPath := range sqlRepoPaths {
		// filepath.Rel: 절대 경로를 프로젝트 루트 기준 상대 경로로 변환한다.
		// 예: "/home/user/project/internal/domain/user/subdomain/core/repo"
		//   → "internal/domain/user/subdomain/core/repo"
		relPath, err := filepath.Rel(cfg.ProjectRoot, repoPath)
		if err != nil {
			continue
		}
		cleaned := filepath.Clean(relPath)

		// sqlc.yaml의 등록된 경로 Set에 이 경로가 없으면 → 누락된 항목
		if !registeredPaths[cleaned] {
			violations = append(violations, report.Violation{
				Rule:     "sqlc/missing-sqlc-entry",
				Severity: report.Error,
				Message:  fmt.Sprintf("repo 디렉토리 %q에 .sql 파일이 있지만 sqlc.yaml에 등록되지 않음", cleaned),
				File:     repoPath,
				Fix:      "sqlc.yaml의 sql 배열에 해당 경로를 추가하고 'make sqlc-gen' 실행",
			})
		}

		// ── 규칙 2: sqlc/manual-code-in-sqlc-repo ──
		// 이 repo/ 디렉토리에 수기 작성된 .go 파일이 있는지 확인한다.
		// (.sql 파일이 있는 repo/는 sqlc가 관리하는 디렉토리이므로
		//  모든 .go 파일은 sqlc가 자동 생성한 것이어야 한다)
		violations = append(violations, checkManualGoFiles(repoPath)...)
	}

	// ── 규칙 3: sqlc/orphan-sqlc-entry ──
	// sqlc.yaml에는 있지만 실제 디렉토리에 .sql 파일이 없는 "유령 항목"을 찾는다.
	//
	// 먼저 .sql 파일이 있는 repo/ 경로들을 Set으로 만든다 (위에서 찾은 경로들).
	sqlRepoSet := make(map[string]bool)
	for _, p := range sqlRepoPaths {
		relPath, err := filepath.Rel(cfg.ProjectRoot, p)
		if err != nil {
			continue
		}
		sqlRepoSet[filepath.Clean(relPath)] = true
	}
	// sqlc.yaml에 등록된 각 경로에 대해, 실제 .sql 파일이 있는지 확인한다.
	for registeredPath := range registeredPaths {
		if !sqlRepoSet[registeredPath] {
			violations = append(violations, report.Violation{
				Rule:     "sqlc/orphan-sqlc-entry",
				Severity: report.Warning,
				Message:  fmt.Sprintf("sqlc.yaml에 %q 항목이 있지만 해당 경로에 .sql 파일이 없음", registeredPath),
				File:     filepath.Join(cfg.ProjectRoot, "sqlc.yaml"),
				Fix:      "해당 도메인이 삭제되었다면 sqlc.yaml에서 항목을 제거",
			})
		}
	}

	return violations
}

// ──────────────────────────────────────────────
// sqlc.yaml 파싱 헬퍼
// ──────────────────────────────────────────────

// parseSqlcYaml은 프로젝트 루트의 sqlc.yaml 파일을 읽어서 sqlcConfig 구조체로 변환한다.
//
// Go에서 YAML 파싱 흐름:
//  1. os.ReadFile로 파일 전체를 바이트 슬라이스([]byte)로 읽는다
//  2. yaml.Unmarshal로 바이트 슬라이스를 구조체로 변환한다 (역직렬화)
//
// NestJS 비유:
//
//	const content = fs.readFileSync("sqlc.yaml", "utf-8");
//	const config = yaml.parse(content);  // js-yaml 사용
//
// Go에서는 yaml.Unmarshal이 구조체 태그(`yaml:"..."`)를 보고
// YAML 키와 Go 필드를 자동으로 매핑해준다.
func parseSqlcYaml(projectRoot string) (*sqlcConfig, error) {
	// os.ReadFile: 파일 전체를 한 번에 메모리로 읽는다.
	// 작은 설정 파일이므로 전체를 한 번에 읽어도 문제없다.
	data, err := os.ReadFile(filepath.Join(projectRoot, "sqlc.yaml"))
	if err != nil {
		return nil, fmt.Errorf("sqlc.yaml 읽기 실패: %w", err)
	}

	var cfg sqlcConfig
	// yaml.Unmarshal: YAML 바이트를 Go 구조체로 역직렬화한다.
	// &cfg로 포인터를 전달해야 함수 내부에서 값을 채울 수 있다.
	// (Go는 기본적으로 값 복사이므로, 원본을 수정하려면 포인터가 필요하다)
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("sqlc.yaml 파싱 실패: %w", err)
	}
	return &cfg, nil
}

// ──────────────────────────────────────────────
// .sql 파일이 있는 repo/ 디렉토리 탐색
// ──────────────────────────────────────────────

// findSQLRepoPaths는 internal/domain/ 아래의 모든 repo/ 디렉토리를 탐색하여
// .sql 파일이 하나라도 있는 디렉토리의 절대 경로 목록을 반환한다.
//
// filepath.WalkDir 패턴 설명:
//
//	filepath.WalkDir는 디렉토리 트리를 재귀적으로 순회하는 Go 표준 라이브러리 함수다.
//	Node.js의 fs.readdirSync + 재귀 호출을 하나의 함수로 합쳐놓은 것과 비슷하다.
//
//	인자로 "콜백 함수"를 받아서, 발견되는 모든 파일/디렉토리에 대해 호출한다.
//	콜백이 filepath.SkipDir를 반환하면 해당 디렉토리의 하위 항목은 건너뛴다.
//
//	순회 순서: 깊이 우선(DFS), 알파벳 순
//
// 탐색 전략:
//
//	모든 파일을 하나하나 확인하는 대신, "repo"라는 이름의 디렉토리를 찾아서
//	그 안에 .sql 파일이 있는지만 확인한다. 효율적으로 탐색하기 위해
//	repo/ 디렉토리를 찾으면 filepath.SkipDir로 더 깊이 들어가지 않는다.
func findSQLRepoPaths(projectRoot string) []string {
	var result []string

	domainRoot := filepath.Join(projectRoot, "internal", "domain")
	// internal/domain/ 디렉토리가 없으면 (프로젝트 초기) 빈 결과 반환
	if _, err := os.Stat(domainRoot); os.IsNotExist(err) {
		return nil
	}

	// filepath.WalkDir로 domainRoot 아래를 재귀 순회한다.
	// 콜백 함수의 파라미터:
	//   path: 현재 항목의 전체 경로
	//   d: 디렉토리 엔트리 (이름, 타입 등)
	//   err: 이 항목에 접근할 때 발생한 에러 (권한 문제 등)
	//
	// 반환값:
	//   nil → 순회 계속
	//   filepath.SkipDir → 이 디렉토리의 하위 항목 건너뛰기
	//   그 외 에러 → 순회 중단
	//nolint:errcheck,gosec // WalkDir 콜백 내에서 에러를 개별 처리한다 (건너뛰기).
	filepath.WalkDir(domainRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil //nolint:nilerr // 접근 에러가 발생한 항목은 건너뛰고 순회를 계속한다.
		}

		// 디렉토리가 아니거나, 이름이 "repo"가 아니면 건너뛴다
		if !d.IsDir() || d.Name() != "repo" {
			return nil
		}

		// "repo" 디렉토리를 찾았으니, 안에 .sql 파일이 있는지 확인한다
		entries, readErr := os.ReadDir(path)
		if readErr != nil {
			return nil //nolint:nilerr // 읽기 실패한 디렉토리는 건너뛰고 순회를 계속한다.
		}
		for _, entry := range entries {
			// .sql 확장자를 가진 파일이 하나라도 있으면 이 디렉토리를 결과에 추가
			if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".sql") {
				result = append(result, path)
				// filepath.SkipDir: 이 repo/ 안의 하위 디렉토리는 탐색할 필요 없음
				return filepath.SkipDir
			}
		}
		return nil
	})

	return result
}

// ──────────────────────────────────────────────
// 수기 작성 Go 파일 검사
// ──────────────────────────────────────────────

// checkManualGoFiles는 .sql 파일이 있는 repo/ 디렉토리의 모든 .go 파일을 검사하여
// sqlc가 자동 생성한 파일이 아닌 수기 작성 파일을 찾아낸다.
//
// sqlc가 생성한 Go 파일에는 항상 다음 헤더가 포함된다:
//
//	// Code generated by sqlc. DO NOT EDIT.
//
// 이 헤더가 없는 .go 파일은 개발자가 직접 작성한 것이므로 위반으로 보고한다.
//
// 왜 수기 Go 파일을 금지하는가?
//
//	sqlc가 관리하는 repo/ 디렉토리에 수동으로 Go 파일을 추가하면,
//	sqlc가 코드를 재생성할 때 충돌이 발생하거나, 수기 코드가 덮어씌워질 수 있다.
//	비즈니스 로직은 svc/ 레이어에 작성해야 한다.
func checkManualGoFiles(repoPath string) []report.Violation {
	var violations []report.Violation

	entries, err := os.ReadDir(repoPath)
	if err != nil {
		return nil
	}

	for _, entry := range entries {
		// 디렉토리이거나 .go 파일이 아니면 건너뛴다
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") {
			continue
		}

		filePath := filepath.Join(repoPath, entry.Name())
		// sqlc 자동 생성 헤더가 없으면 → 수기 작성 파일
		if !hasSqlcGeneratedHeader(filePath) {
			violations = append(violations, report.Violation{
				Rule:     "sqlc/manual-code-in-sqlc-repo",
				Severity: report.Error,
				Message:  "sqlc를 사용하는 repo/ 디렉토리에 수기 작성된 Go 파일 발견: " + entry.Name(),
				File:     filePath,
				Fix:      "repo/의 Go 코드는 sqlc가 자동 생성해야 한다. 비즈니스 로직은 svc/ 레이어에 작성",
			})
		}
	}

	return violations
}

// ──────────────────────────────────────────────
// 생성 파일 헤더 확인
// ──────────────────────────────────────────────

// hasSqlcGeneratedHeader는 파일의 처음 5줄 안에 sqlc 자동 생성 헤더가 있는지 확인한다.
//
// Go의 코드 생성 컨벤션:
//
//	Go 생태계에서는 도구가 자동 생성한 파일의 상단에 특정 주석을 넣는 관례가 있다.
//	예: "// Code generated by <도구명>. DO NOT EDIT."
//	이 관례는 go generate 문서에도 명시되어 있다.
//	golangci-lint 같은 린터도 이 주석이 있으면 해당 파일의 린트를 건너뛴다.
//
// 왜 5줄만 확인하는가?
//
//	sqlc가 생성하는 파일의 헤더 형태:
//	  // Code generated by sqlc. DO NOT EDIT.
//	  // versions:
//	  //   sqlc v1.xx.x
//	  package repo
//	헤더는 항상 파일 상단에 있으므로, 처음 5줄이면 충분하다.
//	파일 전체를 읽지 않아 성능상 이점이 있다.
//
// defer f.Close() 패턴:
//
//	Go에서 파일을 열면 반드시 닫아야 한다 (리소스 누수 방지).
//	defer 키워드를 쓰면, 현재 함수가 종료될 때 자동으로 실행된다.
//	NestJS의 finally 블록과 비슷하지만, 선언 위치가 더 자유롭다.
//	예: defer f.Close()  → 이 함수가 return될 때 f.Close()가 호출됨
func hasSqlcGeneratedHeader(filePath string) bool {
	file, err := os.Open(filePath)
	if err != nil {
		return false // 파일을 열 수 없으면 헤더 없는 것으로 간주
	}
	// defer: 이 함수가 끝날 때(어떤 경로로 return하든) file.Close()를 실행한다.
	// _ = file.Close()에서 _는 에러 반환값을 무시하는 Go 관용 표현이다.
	defer func() { _ = file.Close() }()

	// bufio.Scanner: 파일을 줄 단위로 효율적으로 읽는 도구다.
	// 내부적으로 버퍼를 사용해서 디스크 I/O 횟수를 줄인다.
	// Node.js의 readline.createInterface와 비슷하다.
	scanner := bufio.NewScanner(file)
	// sqlcHeaderMaxLines는 sqlc 생성 헤더를 검색할 최대 줄 수다.
	// sqlc 헤더는 항상 파일 상단에 위치하므로 5줄이면 충분하다.
	const sqlcHeaderMaxLines = 5

	lineCount := 0
	for scanner.Scan() {
		lineCount++
		if lineCount > sqlcHeaderMaxLines {
			break // 5줄을 넘으면 더 이상 확인할 필요 없다
		}
		// strings.Contains: 문자열 안에 특정 부분 문자열이 있는지 확인한다.
		// JavaScript의 str.includes()와 동일하다.
		if strings.Contains(scanner.Text(), "Code generated by sqlc. DO NOT EDIT.") {
			return true
		}
	}
	return false
}
